Models/ModuleEntry.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace stacsnet.Models {

    [Bind("Module, Year, Folder")]
    public class ModuleEntry {

        [DisplayName( "Module code: ") ]
        [Required( ErrorMessage = "Module code is required")]
        [RegularExpression("^[A-Z]{2}[1-9][0-9]{4}$", ErrorMessage = "Module code is invalid")]
        public string Module { get; set; }

        [DisplayName( "Year: ") ]
        [Required( ErrorMessage = "Year is required")]
        [RegularExpression("^(19|20)[0-9]{2}$", ErrorMessage = "Year is invalid")]
        public string Year { get; set; }

        [DisplayName( "Folder: ") ]
        [Required( ErrorMessage = "Folder is required")]
        [MinLength(2, ErrorMessage = "{0} must be at least {1} character")]
        [StringLength(10, ErrorMessage = "{0} cannot exceed {1} characters")]
        public string Folder { get; set; }
    }
}

Models/QAPost.cs
using System;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc; 
using System.ComponentModel; 

namespace stacsnet.Models
{
    [Bind("module_code","year","title","uname","text","tags","pid","replyname")] 
    public class QAPost
    {
        [DisplayName("Username ")]
        public string uname { get; set; }

        [Required]
        public DateTime date { get; set; }

        [DisplayName("Tags (comma seperated list) ")]
        public string tags { get; set; }

        [Required]
        [DisplayName("Content* ")]
        public string text { get; set; }

        [Required]
        [DisplayName("Title* ")]
        public string title { get; set; }

        [Key]
        [ScaffoldColumn(false)]
        public string id { get; set; }

        [Required]
        public string pid { get; set; }


        public QAThread Children() {
            QAThread thread = new QAThread();
            using (var context = new SnContext ()) {
                thread.posts = context.QAPosts.Where(p => p.pid == id).ToList();
                thread.header = this;
                context.SaveChanges();
            }
            return thread;
        }   
    }
}

Controllers/QAController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using stacsnet.Models;
using stacsnet.Util;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel; 
using System.Diagnostics;


namespace stacsnet.Controllers
{
    [BasicAuthorize("stacsnet.com")]
    public class QAController : Controller
    {
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Comment(string return_url, QAPost post) {
            using (var context = new SnContext ()) {
                post.date = DateTime.Now;
                context.QAPosts.Add(post);
                context.SaveChanges();
                Flash( "Comment posted", "success");
            }
            return Redirect(return_url); 
        }

        public IActionResult Index() {
            var thread = findThread( "0" );
            ViewBag.Title = ViewBag.Subtitle = "QA board ";
            ViewBag.ButtonText = "Post a question or comment";
            ViewBag.CommentText = "posts";
            return View( thread );
        }

        public IActionResult Thread( string pid ) {
            if ( pid.Equals("0") ) 
                return RedirectToAction( "Index" );
            ViewBag.Title = ViewBag.Subtitle = "QA board";
            ViewBag.ButtonText = "Reply";
            ViewBag.CommentText = "replies";
            QAThread thread = findThread( pid );
            if ( thread == null ) {
                Flash( "No matching QA posts were found", "danger" );
                return RedirectToAction( "Index" );
            }
            else  
                return View( "Index", thread );

        }

        private IActionResult Error(int status, string error_msg ) =>
            RedirectToRoute( "Error", new { status = status, error_msg = error_msg } );

        private void Flash( string error_msg, string css ) {
            TempData[ "Flash" ] = error_msg;
            TempData[ "FlashCss" ] = css;
        }

        private QAThread findThread( string pid ) {
            QAPost header = null;
            List<QAPost> posts = new List<QAPost>();
            var context = new SnContext ();

            if ( pid.Equals("0")) 
                header = Static.FIRST_POST;
            else
                header = context.QAPosts.Where(p => p.id == pid).FirstOrDefault();
            
            if (header == null )
                return null;
            else {
                posts.AddRange( context.QAPosts.Where(p => p.pid == pid) );

                return new QAThread() {
                    header = header,
                    posts = posts
                };
            }
        }
    }
}

Controllers/RegisterController.cs
using System;
using System.Net;
using System.Net.Mail;
using System.Linq;
using System.Diagnostics;
using stacsnet.Util;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using stacsnet.Models;

namespace stacsnet.Controllers
{
    public class RegisterController : Controller
    {
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Submit(Account account)
        {
            string key = Guid.NewGuid().ToString();
            using (var acontext = new SnContext() ) {
                var model = new Account();
                var old_account = acontext.Accounts.FirstOrDefault( a => a.email == account.email);
                if (old_account != null) {
                    if (old_account.verified) {
                        string msg = "The email address " + account.email
                        + " has been registered and confirmed. The username and password you supplied when creating the account"
                        + " are valid to authenticate you on this site." ;
                        Flash( msg, "success" );
                    }
                    else {
                        string msg = "The email address " + account.email + "@st-andrews.ac.uk has already submitted for registration. " 
                        + "Please check your emails from stacnet@gmail.com and open the confirmation link supplied.";
                        Flash( msg, "warning" );
                    }
                }
                else {
                    Send(account.email,account.uname, key);
                    var hasher = new PasswordHasher<Account>();
                    account.key = key;
                    account.pwhash = hasher.HashPassword(account, account.pwhash);
                    account.verified = false;
                    acontext.Accounts.Add(account);
                    acontext.SaveChanges();
                    string msg = "The email address " + account.email + "@st-andrews.ac.uk" + " was succesfully submitted for registration. "
                    + "Please check your emails from stacsnet@gmail.com and open the confirmation link supplied.";
                    Flash( msg, "info" );
                }
                return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult Confirm(string key)
        {
            ViewBag.Title = "confirm your account";
            
            using (var acontext = new SnContext()) {
                var account = acontext.Accounts.FirstOrDefault( a => a.key == key);
                if (account == null) {
                    string msg = "Your account was not registered or could not be found. Please submit "
                    + "for registration again.";
                    Flash( msg, "danger");
                }
                else {
                    if (account.verified == false) {
                        account.verified = true;
                        acontext.Accounts.Update(account);
                        acontext.SaveChanges();
                    }
                
                    string msg = "The account " + account.email + "@st-andrews.ac.uk " + "(" 
                    + account.uname + ") " + "has been succesfuly registered and confirmed. Please save your password, "
                    + "you are authenticated to access all features of stacsnet";
                    Flash( msg, "success");
                }
            }         
            return RedirectToAction("Index", "Home");
        }

        private IActionResult Error(int status, string error_msg ) =>
            RedirectToRoute( "Error", new { status = status, error_msg = error_msg } );

        private void Flash( string error_msg, string css ) {
            TempData[ "Flash" ] = error_msg;
            TempData[ "FlashCss" ] = css;
        }
        
        private void Send(string email, string uname, string key) {

            var fromAddress = new MailAddress("stacsnet@gmail.com", "Stacsnet Admin");
            var toAddress = new MailAddress(email + "@st-andrews.ac.uk", uname);
            const string fromPassword = "staccy365";
            const string subject = "Verify your stacsnet account";
            string href = Static.URL + "/Register/" + key;
            string body = System.IO.File.ReadAllText("Views/Shared/_Email.html")
                                    .Replace("{{uname}}",uname)
                                    .Replace("{{href}}", href);
                                    
            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromAddress.Address, fromPassword)
            };
            using (var message = new MailMessage(fromAddress, toAddress)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
            {
                smtp.Send(message);
            }
        }
    }
}

Controllers/ReportController.cs
using System;
using System.Collections;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using stacsnet.Models;
using stacsnet.Util;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel; 

namespace stacsnet.Controllers
{
    [BasicAuthorize("stacsnet.com")]
    public class ReportController : Controller
    {
        [HttpGet]
        public IActionResult Index(string module_code, string year) {

            ViewBag.Modules = Static.MODULES;
            ViewBag.Years = Static.YEARS;
        

            if ( !Static.isYear( year ) || !Static.isModule( module_code ) ) {
                string error_msg =  "Invalid selection " + "(" + module_code + ", " + year + ").";
                string default_module = Static.MODULES.First();
                string default_year = Static.YEARS.First();
                Flash(error_msg, "danger");
                return RedirectToAction( "Index", new { module_code = default_module, year = default_year} );

            }
            else {
                ViewBag.Module = module_code;
                ViewBag.Year = year;
                ViewBag.Title = "Grade reports";
                ViewBag.Subtitle = "Grade reports for " + module_code + " (" + year + ")";
                return View( loadReports( module_code, year ));
            }
        }


        [HttpPost]
        public IActionResult Submit(string return_url, GradeReport report) {
            if (ModelState.IsValid) {
                using(var context = new SnContext ()) {
                    context.GradeReports.Add(report);
                    context.SaveChanges();
                }
                Flash( "submission received", "success" );
            }
            else 
                Flash( "submission not received", "danger");
            
            return Redirect(return_url);
        }

        private Dictionary<string, ReportData> loadReports( string module_code, string year ) {
                using (var context = new SnContext()) {
                    var allreports = context.GradeReports.Where(g => g.code == module_code && g.Year == year).ToList();
                    var reports = new Dictionary<string, ReportData>();
                    var mincount = 3;
                    foreach (var type in Enum.GetNames(typeof(GradeType))) {
                        var typedreports = allreports.Where(g => g.Type.ToString() == type).ToList();
                        var count = typedreports.Count();
                        if (count < mincount) {
                        reports.Add(type, new ReportData {
                                count = count,
                                min = mincount,
                                reports = new List<ArrayList>()
                            }); 
                        }
                        else {
                            var list = new List<ArrayList>();

                            foreach (var row in typedreports) {
                                var innertype = type;
                                if (type == "Practical")
                                    innertype = "W" + row.Week;
                                list.Add( new ArrayList{ innertype, row.Grade } );
                            }

                            reports.Add(type, new ReportData {
                                count = count,
                                min = mincount,
                                reports = list
                            });
                        }
                    }
                return reports;
            }
        }

        private IActionResult Error(int status, string error_msg ) =>
            RedirectToRoute( "Error", new { status = status, error_msg = error_msg } );

        private void Flash( string error_msg, string css ) {
            TempData[ "Flash" ] = error_msg;
            TempData[ "FlashCss" ] = css;
        }

    }
}

Views/Shared/_FileSearch.cshtml
<div id='searchbox' class="col-sm-4">
    @Html.TextBox("tagsin", null, new { @class = "form-control",
                            placeholder="Search...",
                            @id = "filesearch_in" }) 
    <div id='datebox'>
        <p>
            Ascending:&nbsp;&nbsp;@Html.RadioButton("date_in","asc",true)
        </p>
        <p>
            Descending:&nbsp;&nbsp;@Html.RadioButton("date_in","dsc")
        </p>
        </div>
    <button id='filesearch_btn' class="btn btn-primary">Filter</button> 
</div>

Views/Shared/_FileUpload.cshtml
@using (Html.BeginForm("FileUpload", "Modules", FormMethod.Post, new {  action = "/Upload", 
                                                                            enctype = "multipart/form-data", 
                                                                            @id = "form"  }))
{ 
    <input type="file" id="files_in" name="files" multiple size="50"/>
    <br>
    <input type="hidden" value=@Model.FullName  name="target_path"/>
    <input type="hidden" value=@Context.Request.GetDisplayUrl() name="return_url"/>
    <input type="submit" class='btn btn-secondary' name="Submit" id="submit" value="Upload" />
}
<p class="file-info-box">

</p>

Views/Shared/_Flash.cshtml
@if( TempData.ContainsKey( "Flash" ) ) {
    string msg = TempData[ "Flash" ].ToString();
    string css = TempData.ContainsKey( "FlashCss" ) ? TempData[ "FlashCss" ].ToString() : "info";
    <div class="flash alert alert-@css">
        <h5 class="font-weight-bold">
            @msg
            <i class="btn-flash fa fa-times" style="float:right"></i>
        <h5>
    </div>
}

Views/Shared/_Footer.cshtml
<!-- Footer -->
<hr>
    <div class="text-center center-block">
        <p class="txt-railway">- &copy; Noah Florin-Sefton 2018 -</p>
        <br />
            <a href="https://www.linkedin.com/in/057368162/"><i class="fa fa-linkedin-square fa-3x social"></i></a>
            <a href="https://github.com/NFS002/stacsnet"><i class="fa fa-github-square fa-3x social"></i></a>
    </div>
<hr>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Stacsnet - @ViewBag.Title</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        @RenderSection("Styles", false)
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="icon" href="~/favicon/favicon.ico" />
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Stacsnet</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Modules" asp-action="All_years">Modules</a></li>
                    <li><a asp-controller="QA" asp-action="Index">Q & A</a></li>
                    @{ 
                        var year = Static.YEARS.First();
                        var module = Static.MODULES.First();
                    }
                    <li><a asp-controller="Report" asp-action="Index" asp-route-module_code="@module" asp-route-year="@year">
                        Grade averages
                    </a></li>
                    <li><a href="https://github.com/NFS002/stacsnet/wiki">Wiki</a></li>
                    <li><a id='privacylink'>Your privacy</a></li>
                    <li><a href='https://github.com/NFS002/stacsnet/issues'>Bugs & feature requests</a></li>    
                </ul>
                <a href="http://nfs002.github.io">
                <div class="home-button">
                        <i class="fa fa-arrow-left"></i>
                        <img height="50" src="~/img/rsz_logo-white.png">
                </div>
                </a>
            </div>
        </div>
    </nav>
    
    <div class="container body-content">
        <noscript>
            <br>
            <p class="alert alert-danger">Please enable javascript to access stacsnet.</p>
            <style type="text/css">
            .page-wrapper { display: none}
            </style>
        </noscript>
        <div class="page-wrapper">
            @RenderBody()
        </div>
        <div id="privacydialog" title="Our approach to your privacy">
            <p>
                Stacsnet is designed to preserve the anonyimity of the users of stacnet.
                Various features are in place to ensure that the identity of stacsnet users 
                cannot be linked to their university account, whilst https helps to ensure 
                that any sensitive data cannot be intercepted whilst in transmission. 
            </p>
        </div>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="~/js/global/yourprivacy.js"></script>
        <script src="~/js/global/flash.js"></script>
        @RenderSection("Scripts", false)
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="~/js/site.min.js"></script>
        @RenderSection("Scripts", false)
    </environment>
</body>
</html>

Views/Shared/_ModuleEntryForm.cshtml
@model stacsnet.Models.ModuleEntry;

<div class="row" id="modalform" title='Submit your grades'>
      @using (Html.BeginForm("ModuleEntry","Home",FormMethod.Post, new { enctype = "multipart/form-data"}))
        {
            @Html.AntiForgeryToken() 
            <div class='col-sm-6'>
                
                <br>
                
            </div>
            <div class='col-sm-6'>
                
                <br>
              
                <br>
                
            </div>
            <div class='col-sm-12'>
                <br>
                
                @Html.ValidationSummary()
                <input id='submitbtn' class='btn btn-primary' type='submit'/>
                <div id='date'>
                    @DateTime.Now
                </div>
            </div>
            @Html.Hidden("return_url", @Context.Request.GetDisplayUrl())
        }
</div>

Views/Shared/_PostErrorButton.cshtml
<a asp-route="Error">
    <h3 class="btn btn-lg btn-primary">
        Ask a new question
    </h3>
</a>

Views/Shared/_QAHeader.cshtml
@model stacsnet.Models.QAPost
<div class="row container">
    <div class='col-sm-8'>
        @if (!Model.date.Equals(DateTime.MinValue)) {
            <a asp-controller="QA" asp-action="Index">
                <button class="btn btn-outline-secondary" style="margin-top:13px;float:right">
                    <h5><i class="fa fa-xl fa-arrow-left"></i>Back to all posts</h5>
                </button>
            </a>
        }
        <h1 class="text-uppercase">Stacsnet</h1>
        <h3> @ViewBag.Subtitle</h3>
        @if (!string.IsNullOrEmpty(Model.title)) {
            <span><em><small>@Model.title</small></em></span>
        }
        @if (!string.IsNullOrEmpty(Model.uname)) {
            <span><em><small style="float:right">
                @Model.uname
            </small></em></span>
            <br>
        }
        @if (!string.IsNullOrEmpty(Model.text)) {
            <h5 style="border-bottom: 1px solid #D3D3D3;padding: 5px;max-height: 150px;overflow-y:auto;">
                @Model.text
            </h5>
        }
        @if (!Model.date.Equals(DateTime.MinValue)) {
            <br>
                <span><em><small>@Model.date</small></em></span>
            <br>
        }
        @if (!string.IsNullOrEmpty(Model.tags)) {
            var tagarr = Model.tags.Split(",");
            var taglist = tagarr.ToList();
            if(taglist.Count() > 15){
                taglist = taglist.Take(14).ToList();
            }
            foreach (var tag in taglist)
               {
                   <div class="btn-tag">
                        <i class="fa fa-lg fa-hashtag"></i>
                        @tag
                   </div>
               } 
        }
        <br>
        <h3 id='commentbtn'
            class='reply-btn btn btn-lg btn-primary'>
            @ViewBag.ButtonText
         </h3>
    </div>
    <div id='searchbox' class='col-sm-4'>
        @Html.Label("unamein","Username")
        @Html.TextBox("unamein", null, new { @class = "form-control input-uname",
                                        @id = "search_uname_in" })
        @Html.Label("tt","Title/Text")
        @Html.TextBox("tt", null, new { @class = "form-control",
                                        @id = "search_tt_in" })
        @Html.Label("tagsin","Tags (e.g 'java,oop,tree')")
        @Html.TextBox("tagsin", null, new { @class = "form-control",
                                        @id = "search_tags_in" }) 
        <div id='datebox'> 
            <p>
                Date Ascending:&nbsp;&nbsp;@Html.RadioButton("Date","ascending",true)
            </p>
            <p>
                Date Descending:&nbsp;&nbsp;@Html.RadioButton("Date","descending")
            </p>
        </div>
        <button id='searchbtn' class="btn btn-primary">Filter</button> 
    </div>
</div>
</div>
<div class="row container">
    @{ await Html.RenderPartialAsync("_Flash"); }
</div>
<hr>
<div class="row" id="commentform" title='Post a comment' >
    @{  
        Model.text = "";
        await Html.RenderPartialAsync("_QAPost", @Model); 
    }
</div>

Views/Shared/_QAPost.cshtml
@model stacsnet.Models.QAPost 
@{
    var placeholder = @Model.tags;
    @Model.tags = "";
}
@using (Html.BeginForm("Comment","QA", FormMethod.Post, new { enctype = "multipart/form-data",
                                                                onsubmit="return bindtags()"}))
{
@Html.AntiForgeryToken()
    var date = DateTime.Now;
    var datestr = date.ToString("g");
    var message = "";
    if (!string.IsNullOrEmpty(Model.uname)) {
        message = "@" + Model.uname;
        Model.uname = "";
    }
<div id='date'>
    @datestr
        <div id='replybox'>
        @message
    </div>
</div>
@Html.HiddenFor(m => m.pid, new { @id = "pidin" })
@Html.LabelFor(m => m.title, new {style="color:#900" })
@Html.TextBoxFor(m => m.title, new { @class = "form-control",
                                @id = "titlein",
                                value = "@Model.title"}) 
<br>
@Html.LabelFor(m => m.uname)
@Html.TextBoxFor(m => m.uname, new { @class = "form-control input-uname",
                                    @id = "unamein",
                                    placeholder="anon"}) 
<br>
@Html.LabelFor(m => m.tags)
<span id='tagserr' style="color:#911;float:right;font-weight:700"></span>
@Html.TextBoxFor(m => m.tags, new { type="hidden",
                                    @id="realtagsin" })
<input class="form-control" placeholder="@placeholder" id="tagsin">

<br>
<div id='tags-display-box'>

</div>
@Html.LabelFor(m => m.text, new { style="color:#900" })
@Html.TextAreaFor(m => m.text, new { @class = "form-control",
                                rows="10",
                                @id="textarea" })

@Html.Hidden("return_url", @Context.Request.GetDisplayUrl())

<br/>
<input id='submitbtn' class='disabled btn btn-primary' type='submit'/>
}

Views/Shared/_RegisterForm.cshtml
@model Account;

@using (Html.BeginForm("Submit","Register", FormMethod.Post, new { enctype = "multipart/form-data"})){
@Html.AntiForgeryToken()
<div>
    @Html.LabelFor(m => m.email, new { style = "display:block"})
    @Html.TextBoxFor(m => m.email, new { @class = "input-sm form-control",
                                        style="display:inline" })
    <span>@@st-andrews.ac.uk</span>
    <br>
    @Html.ValidationMessageFor(m => m.email, "", new { @class = "text-danger" })
   
    @Html.LabelFor(m => m.uname, new { style = "display:block"})
    @Html.TextBoxFor(m => m.uname, new { @class = "form-control input-uname"}) 
    @Html.ValidationMessageFor(m => m.uname, "", new { @class = "text-danger" })
    @Html.LabelFor(m => m.pwhash, new { style = "display:block"})
    @Html.TextBoxFor(m => m.pwhash, new { @class = "input-sm form-control", type="password" }) 
    @Html.ValidationMessageFor(m => m.pwhash, "", new { @class = "text-danger" })
    <br>
    <input id='submitbtn' value='Register' class='btn btn-primary' type='submit'/>
</div>
}

Views/Shared/_ReportForm.cshtml
@model stacsnet.Models.GradeReport
<div class="row" id="modalform" title='Submit your grades'>
      @using (Html.BeginForm("Submit","Report",FormMethod.Post, new { enctype = "multipart/form-data"}))
        {
            @Html.AntiForgeryToken() 
            <div class='col-sm-6'>
                @Html.LabelFor(m => m.Type)
                @Html.DropDownListFor(m => m.Type, new SelectList(Enum.GetValues(typeof(GradeType))),new { @class = "input-sm form-control",
                                                                                                        @id= "input-gradetype" })
                <br>
                @Html.LabelFor(m => m.Week)
                @Html.TextBoxFor(m => m.Week, new { @class="input-sm form-control",
                                                    @type = "number",
                                                    max = "13",
                                                    @id = "input-week",
                                                    min = "1",
                                                    step = "1"  }) 
            </div>
            <div class='col-sm-6'>
                @Html.LabelFor(m => m.Grade)
                @Html.TextBoxFor(m => m.Grade, new { @class="input-sm form-control",
                                                @type = "number",
                                                @id = "input-grade",
                                                max = "20",
                                                min = "0",
                                                step = "1" }) 
                <br>
                @Html.LabelFor(m => m.code)
                @Html.TextBoxFor(m => m.code, new { @class="input-sm form-control",
                                                        @id = "input-module" })
                <br>
                @Html.LabelFor(m => m.Year)
                @Html.TextBoxFor(m => m.Year, new { @class="input-sm form-control",
                                                    name = "year" })  

            </div>
            <div class='col-sm-12'>
                <br>
                @Html.LabelFor(m => m.descr)
                @Html.TextBoxFor(m => m.descr, new { @class = "form-control",
                                                    placeholder = "E.g 'Java http server...' "})
                @Html.ValidationSummary()
                <input id='submitbtn' class='btn btn-primary' type='submit'/>
                <div id='date'>
                    @DateTime.Now
                </div>
            </div>
            @Html.Hidden("return_url", @Context.Request.GetDisplayUrl())
        }
</div>

Views/Shared/_TitleSection.cshtml
<div class="row justify-content-between container">
    <div class="col-sm-4 no-padding">
        <h1 class="text-uppercase">Stacsnet</h1>
        <h3> @ViewBag.Subtitle </h3>
    </div>
    <div class="col-sm-8 no-padding">
        @{ await Html.RenderPartialAsync("_Flash"); }
    </div>
</div>
<hr>